/**
 * Central site configuration.
 *
 * This is the ONLY place launch-critical values live. Anything marked
 * `OWNER DECISION` is a business fact the repository cannot supply; the pages
 * are written so that a missing value is simply absent rather than rendered as
 * a placeholder. Nothing here is fetched at runtime — it is compiled into the
 * pages.
 */

/** ------------------------------------------------------------------------
 *  Identity
 *  --------------------------------------------------------------------- */
export const site = {
  name: "Videflo",
  /** Canonical origin, no trailing slash. Used for metadata, sitemap, robots. */
  url: "https://videflo.com",
  tagline: "Capture Today. Cherish Forever.",
  brandPhrase: "Life in Tapes.",
  description:
    "Create continuous Tapes from life’s moments and revisit the memories that matter most.",
  /** Short description used for social cards. */
  socialDescription:
    "Videflo turns life’s moments into continuous Tapes you can revisit for years to come.",
  locale: "en_US",
} as const;

/**
 * The social sharing card used by every page.
 *
 * `/opengraph-image` is the route generated by `src/app/opengraph-image.tsx` at
 * build time. To use designed artwork instead, point `url` at a file in
 * `public/` and delete that file — see ASSETS.md.
 */
export const ogImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Videflo | Capture Today. Cherish Forever.",
} as const;

/** ------------------------------------------------------------------------
 *  Contact
 *  --------------------------------------------------------------------- */
export const contact = {
  /**
   * The one Videflo inbox confirmed to exist and be monitored (owner
   * confirmation, 2026-09-19). Every public contact on the site — support,
   * privacy requests and legal notices — resolves to it. `support@`, `legal@`
   * and `privacy@` were never created; do not reintroduce them without the
   * mailboxes existing first.
   */
  supportEmail: "admin@videflo.com",
  /** Legal notices and the Terms' informal-resolution step. Same inbox. */
  legalEmail: "admin@videflo.com",
  /** Privacy and data-rights requests. Same inbox. */
  privacyEmail: "admin@videflo.com",
} as const;

/** ------------------------------------------------------------------------
 *  App Store
 *
 *  BEFORE LAUNCH: set `url` to the real App Store product URL, e.g.
 *    url: "https://apps.apple.com/app/videflo/id0000000000"
 *
 *  While `url` is null, every download call to action renders in a complete,
 *  clearly-labelled "coming soon" state instead of pointing at a dead link.
 *  There are no `#` placeholder hrefs anywhere in the site — see
 *  `src/components/ui/AppStoreButton.tsx` for the two rendered states.
 *  --------------------------------------------------------------------- */
export const appStore = {
  url: null as string | null,
  /** Shown beneath download buttons while `url` is null. */
  comingSoonLabel: "Coming soon to the App Store",
  /** Shown when a visitor activates a download button while `url` is null. */
  comingSoonNotice:
    "Videflo isn’t on the App Store yet. Email us and we’ll let you know the day it arrives:",
  /**
   * Brand line beneath every download button. Deliberately not a platform
   * statement: Videflo ships on iPhone first and is planned for Android, so
   * the brand positioning is not tied to a device.
   */
  platformNote: "Made for your memories.",
} as const;

/** ------------------------------------------------------------------------
 *  Subscription and Videflo Cloud
 *
 *  Product facts mirrored from the shipping app (`SubscriptionProducts.swift`,
 *  `CloudStorageCapacity.swift`, `Videflo.storekit`). Videflo sells ONE
 *  auto-renewing monthly subscription that includes Videflo Cloud, at three
 *  storage capacities that are upgrades within the same subscription group.
 *  There is no yearly plan, no lifetime purchase, no free trial and no Family
 *  Sharing. Change these only when the app and App Store Connect change.
 *
 *  `basePriceUSD` is the US App Store price of the 50 GB subscription. It is
 *  the only price written on the site; the App Store shows every price in the
 *  visitor's own currency, and the larger capacities are priced there rather
 *  than here.
 *  --------------------------------------------------------------------- */
export const subscription = {
  basePriceUSD: "$9.99",
  billingPeriod: "month",
  /** The Videflo Cloud allowance included with the base subscription. */
  includedStorageLabel: "50 GB",
  /** Every capacity on sale, smallest first, as the app labels them. */
  storageCapacityLabels: ["50 GB", "100 GB", "250 GB"] as readonly string[],
  /** Days an account may stay over its allowance before it is asked to act. */
  overAllowanceGraceDays: 30,
} as const;

/** ------------------------------------------------------------------------
 *  Availability
 *
 *  Which App Store markets Videflo is offered in. This drives real wording in
 *  the Privacy Policy and Terms — not just a sentence, but which privacy and
 *  consumer-law regimes those documents have to address.
 *
 *  WHEN YOU EXPAND: update `launchMarkets`, and if the new market is in the EEA
 *  or the UK, set `offeredInEeaUk` to true and read the note beside it first.
 *  --------------------------------------------------------------------- */
export const availability = {
  launchMarkets: [
    "the United States",
    "Canada",
    "Australia",
    "New Zealand",
  ] as readonly string[],
  /**
   * Videflo is deliberately NOT offered in the European Economic Area or the
   * United Kingdom at launch.
   *
   * Flipping this to `true` is not only a copy change. Offering the app to
   * people in the EEA or UK is what triggers the GDPR, and with it the question
   * of whether Article 27 requires an EU representative to be appointed (and the
   * UK GDPR a UK representative). Sort that out BEFORE you select those
   * countries in App Store Connect, not after.
   */
  offeredInEeaUk: false,
} as const;

/** ------------------------------------------------------------------------
 *  Social
 *
 *  Add an entry to make a link appear in the footer. Leave the array empty and
 *  the footer omits the social row entirely — no dead icons.
 *  --------------------------------------------------------------------- */
export type SocialLink = { label: string; href: string };

export const socials: readonly SocialLink[] = [
  // { label: "Instagram", href: "https://instagram.com/videflo" },
];

/** ------------------------------------------------------------------------
 *  Legal
 *
 *  The entity is registered in Utah. Values marked OWNER DECISION are business
 *  facts the repository cannot confirm; the legal pages omit a postal address
 *  entirely while `entityAddress` is null rather than printing a placeholder.
 *  --------------------------------------------------------------------- */
export const legal = {
  /**
   * OWNER DECISION — confirm the exact registered name, including punctuation
   * ("Videflo LLC" vs "Videflo, LLC"), against the Utah Division of
   * Corporations filing. The legal pages print this verbatim.
   */
  entityName: "Videflo LLC",
  /** How the entity is described in the legal pages. */
  entityDescription: "a Utah limited liability company",
  /**
   * OWNER DECISION — the public business or registered-agent mailing address.
   * While null, the Contact sections list email only.
   */
  entityAddress: null as string | null,
  /** Governing state for the Terms of Service. */
  governingState: "Utah",
  /** Governing country for the Terms of Service. */
  governingCountry: "United States",
  /** Venue for disputes not resolved informally. */
  venue: "the state and federal courts located in Utah",
  /**
   * Dates shown on the legal pages. Update whenever the documents change.
   * `display` is what visitors read; `iso` feeds <time dateTime>.
   */
  privacy: { display: "September 19, 2026", iso: "2026-09-19" },
  terms: { display: "September 19, 2026", iso: "2026-09-19" },
} as const;

/** ------------------------------------------------------------------------
 *  Navigation
 *  --------------------------------------------------------------------- */
export type NavItem = { label: string; href: string };

export const primaryNav: readonly NavItem[] = [
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Why Videflo", href: "/#why-videflo" },
  { label: "Privacy", href: "/privacy" },
  /**
   * The Help Center is the front door for questions about the app — it is what
   * Videflo's own Settings screen links to. `/support` still exists and is still
   * linked from the footer; it is the contact page behind it.
   */
  { label: "Help", href: "/help" },
];

export const footerNav: readonly NavItem[] = [
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Why Videflo", href: "/#why-videflo" },
  { label: "Help Center", href: "/help" },
  { label: "Contact Support", href: "/support" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Terms of Service", href: "/terms" },
];
