/**
 * Central site configuration.
 *
 * This is the ONLY place launch-critical values live. Anything marked
 * `PLACEHOLDER` must be replaced or confirmed by the owner before the site goes
 * public. Nothing here is fetched at runtime — it is compiled into the pages.
 */

/** ------------------------------------------------------------------------
 *  Identity
 *  --------------------------------------------------------------------- */
export const site = {
  name: "Videflo",
  /** Canonical origin, no trailing slash. Used for metadata, sitemap, robots. */
  url: "https://videflo.com",
  tagline: "Capture Today. Cherish Forever.",
  brandPhrase: "Life in Tapes.",
  description:
    "Create continuous Tapes from life’s moments and revisit the memories that matter most.",
  /** Short description used for social cards. */
  socialDescription:
    "Videflo turns life’s moments into continuous Tapes you can revisit for years to come.",
  locale: "en_US",
} as const;

/**
 * The social sharing card used by every page.
 *
 * `/opengraph-image` is the route generated by `src/app/opengraph-image.tsx` at
 * build time. To use designed artwork instead, point `url` at a file in
 * `public/` and delete that file — see ASSETS.md.
 */
export const ogImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Videflo — Capture Today. Cherish Forever.",
} as const;

/** ------------------------------------------------------------------------
 *  Contact
 *  --------------------------------------------------------------------- */
export const contact = {
  /** Visible support address across the site. */
  supportEmail: "support@videflo.com",
  /**
   * PLACEHOLDER — legal / privacy contact address.
   * Point this at a real, monitored inbox before publishing the legal pages.
   */
  legalEmail: "legal@videflo.com",
  /** PLACEHOLDER — privacy requests inbox. May be the same as legalEmail. */
  privacyEmail: "privacy@videflo.com",
} as const;

/** ------------------------------------------------------------------------
 *  App Store
 *
 *  BEFORE LAUNCH: set `url` to the real App Store product URL, e.g.
 *    url: "https://apps.apple.com/app/videflo/id0000000000"
 *
 *  While `url` is null, every download call to action renders in a complete,
 *  clearly-labelled "coming soon" state instead of pointing at a dead link.
 *  There are no `#` placeholder hrefs anywhere in the site — see
 *  `src/components/ui/AppStoreButton.tsx` for the two rendered states.
 *  --------------------------------------------------------------------- */
export const appStore = {
  url: null as string | null,
  /** Shown beneath download buttons while `url` is null. */
  comingSoonLabel: "Coming soon to the App Store",
  /** Shown when a visitor activates a download button while `url` is null. */
  comingSoonNotice:
    "Videflo isn’t on the App Store yet. Email us and we’ll let you know the day it arrives:",
  /** Platform statement — keep accurate. Videflo is iPhone-only today. */
  platformNote: "Made for iPhone",
} as const;

/** ------------------------------------------------------------------------
 *  Social
 *
 *  Add an entry to make a link appear in the footer. Leave the array empty and
 *  the footer omits the social row entirely — no dead icons.
 *  --------------------------------------------------------------------- */
export type SocialLink = { label: string; href: string };

export const socials: readonly SocialLink[] = [
  // { label: "Instagram", href: "https://instagram.com/videflo" },
];

/** ------------------------------------------------------------------------
 *  Legal — ALL PLACEHOLDERS. Confirm with counsel and business registration.
 *  --------------------------------------------------------------------- */
export const legal = {
  /** PLACEHOLDER — replace with the registered legal entity name. */
  entityName: "Videflo LLC",
  /** PLACEHOLDER — replace with the registered business address. */
  entityAddress: "[Business address to be provided]",
  /** PLACEHOLDER — governing state for the Terms of Service. */
  governingState: "[State to be provided]",
  /** PLACEHOLDER — governing country for the Terms of Service. */
  governingCountry: "United States",
  /**
   * Dates shown on the legal pages. Update whenever the documents change.
   * `display` is what visitors read; `iso` feeds <time dateTime>.
   */
  privacy: { display: "July 26, 2026", iso: "2026-07-26" },
  terms: { display: "July 26, 2026", iso: "2026-07-26" },
} as const;

/** ------------------------------------------------------------------------
 *  Navigation
 *  --------------------------------------------------------------------- */
export type NavItem = { label: string; href: string };

export const primaryNav: readonly NavItem[] = [
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Why Videflo", href: "/#why-videflo" },
  { label: "Privacy", href: "/privacy" },
  { label: "Support", href: "/support" },
];

export const footerNav: readonly NavItem[] = [
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Why Videflo", href: "/#why-videflo" },
  { label: "Support", href: "/support" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Terms of Service", href: "/terms" },
];
